name: Build Kotlin/Native
on: [ push ]

jobs:
  xqt-kotlinx-json-rpc:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3
        with:
          repository: rhdunn/xqt-kotlinx-json-rpc

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build for Kotlin/Native
        run: gradle nativeMainKlibrary

      - name: Test for Kotlin/Native
        run: gradle nativeTest

      - name: Publish Kotlin/Multiplatform to Maven Local
        run: gradle publishKotlinMultiplatformPublicationToMavenLocal

      - name: Publish Kotlin/Native to Maven Local
        run: gradle publishNativePublicationToMavenLocal

      - name: Tar XQT Kotlin JSON-RPC Artifacts
        run: tar -cvf xqt-kotlinx-json-rpc-native-${{ matrix.os }}.tar -C $HOME/.m2/repository/io/github/rhdunn .

      - name: Upload XQT Kotlin JSON-RPC Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xqt-kotlinx-json-rpc-native-${{ matrix.os }}
          path: xqt-kotlinx-json-rpc-native-${{ matrix.os }}.tar

  build:
    needs: xqt-kotlinx-json-rpc
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Download XQT Kotlin JSON-RPC Artifacts
        uses: actions/download-artifact@v3
        with:
          name: xqt-kotlinx-json-rpc-native-${{ matrix.os }}

      - name: Extract XQT Kotlin JSON-RPC Artifacts to Maven Local
        run: |
          mkdir -p $HOME/.m2/repository/io/github/rhdunn
          tar -xvf xqt-kotlinx-json-rpc-native-${{ matrix.os }}.tar -C $HOME/.m2/repository/io/github/rhdunn

      - name: Build for Kotlin/Native
        run: gradle nativeMainKlibrary

      - name: Test for Kotlin/Native
        run: gradle nativeTest
