# Copyright (C) 2023 Reece H. Dunn. SPDX-License-Identifier: Apache-2.0
name: Build Kotlin/JVM
on: [ push ]

jobs:
  xqt-kotlinx-json-rpc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3
        with:
          repository: rhdunn/xqt-kotlinx-json-rpc
          ref: master

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build for Kotlin/JVM
        run: gradle -D jvm.target=${{ matrix.java }} jvmJar

      - name: Test for Kotlin/JVM
        run: gradle -D jvm.target=${{ matrix.java }} jvmTest

      - name: Publish Kotlin/Multiplatform to Maven Local
        run: gradle -D jvm.target=${{ matrix.java }} publishKotlinMultiplatformPublicationToMavenLocal

      - name: Publish Kotlin/JVM to Maven Local
        run: gradle -D jvm.target=${{ matrix.java }} publishJvmPublicationToMavenLocal

      - name: Tar XQT Kotlin JSON-RPC Artifacts
        run: tar -cvf xqt-kotlinx-json-rpc-jvm-${{ matrix.java }}.tar -C ~/.m2/repository/io/github/rhdunn .

      - name: Upload XQT Kotlin JSON-RPC Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xqt-kotlinx-json-rpc-jvm-${{ matrix.java }}
          path: xqt-kotlinx-json-rpc-jvm-${{ matrix.java }}.tar

  build:
    needs: xqt-kotlinx-json-rpc
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Download XQT Kotlin JSON-RPC Artifacts
        uses: actions/download-artifact@v3
        with:
          name: xqt-kotlinx-json-rpc-jvm-${{ matrix.java }}

      - name: Extract XQT Kotlin JSON-RPC Artifacts to Maven Local
        run: |
          mkdir -p ~/.m2/repository/io/github/rhdunn
          tar -xvf xqt-kotlinx-json-rpc-jvm-${{ matrix.java }}.tar -C ~/.m2/repository/io/github/rhdunn

      - name: Build for Kotlin/JVM
        run: gradle -D jvm.target=${{ matrix.java }} jvmJar

      - name: Test for Kotlin/JVM
        run: gradle -D jvm.target=${{ matrix.java }} jvmTest

      - name: Publish Kotlin/JVM to Maven Local
        run: gradle -D jvm.target=${{ matrix.java }} publishJvmPublicationToMavenLocal
