name: Build Kotlin/JS Legacy
on: [ push ]

jobs:
  xqt-kotlinx-json-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3
        with:
          repository: rhdunn/xqt-kotlinx-json-rpc

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build for Kotlin/JS Legacy
        run: gradle jsLegacyJar

      - name: Publish Kotlin/Multiplatform to Maven Local
        run: gradle publishKotlinMultiplatformPublicationToMavenLocal

      - name: Publish Kotlin/JS Legacy to Maven Local
        run: gradle publishJsPublicationToMavenLocal

      - name: Tar XQT Kotlin JSON-RPC Artifacts
        run: tar -cvf xqt-kotlinx-json-rpc-js-legacy.tar -C ~/.m2/repository/xqt-kotlinx-lsp .

      - name: Upload XQT Kotlin JSON-RPC Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xqt-kotlinx-json-rpc-js-legacy
          path: xqt-kotlinx-json-rpc-js-legacy.tar

  build:
    needs: xqt-kotlinx-json-rpc
    runs-on: ubuntu-latest
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Download XQT Kotlin JSON-RPC Artifacts
        uses: actions/download-artifact@v3
        with:
          name: xqt-kotlinx-json-rpc-js-legacy

      - name: Extract XQT Kotlin JSON-RPC Artifacts to Maven Local
        run: |
          mkdir -p ~/.m2/repository/xqt-kotlinx-lsp
          tar -xvf xqt-kotlinx-json-rpc-js-legacy.tar -C ~/.m2/repository/xqt-kotlinx-lsp

      - name: Build for Kotlin/JS Legacy
        run: gradle jsLegacyJar

      - name: Tar Build Artifacts
        run: tar -cvf build-js-legacy-artifacts.tar .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-js-legacy
          path: build-js-legacy-artifacts.tar

  test-node:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    steps:
      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-js-legacy

      - name: Extract Build Artifacts
        run: tar -xf build-js-legacy-artifacts.tar

      - name: Download XQT Kotlin JSON-RPC Artifacts
        uses: actions/download-artifact@v3
        with:
          name: xqt-kotlinx-json-rpc-js-legacy

      - name: Extract XQT Kotlin JSON-RPC Artifacts to Maven Local
        run: |
          mkdir -p ~/.m2/repository/xqt-kotlinx-lsp
          tar -xvf xqt-kotlinx-json-rpc-js-legacy.tar -C ~/.m2/repository/xqt-kotlinx-lsp

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Test for Kotlin/JS Legacy on Node
        run: gradle jsLegacyNodeTest

  test-firefox:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-js-legacy

      - name: Extract Build Artifacts
        run: tar -xf build-js-legacy-artifacts.tar

      - name: Download XQT Kotlin JSON-RPC Artifacts
        uses: actions/download-artifact@v3
        with:
          name: xqt-kotlinx-json-rpc-js-legacy

      - name: Extract XQT Kotlin JSON-RPC Artifacts to Maven Local
        run: |
          mkdir -p ~/.m2/repository/xqt-kotlinx-lsp
          tar -xvf xqt-kotlinx-json-rpc-js-legacy.tar -C ~/.m2/repository/xqt-kotlinx-lsp

      - name: Setup Firefox Latest
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 'latest'

      - name: Test for Kotlin/JS Legacy on Firefox
        run: gradle -D js.browser=Firefox jsLegacyBrowserTest

  test-chrome:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-js-legacy

      - name: Extract Build Artifacts
        run: tar -xf build-js-legacy-artifacts.tar

      - name: Download XQT Kotlin JSON-RPC Artifacts
        uses: actions/download-artifact@v3
        with:
          name: xqt-kotlinx-json-rpc-js-legacy

      - name: Extract XQT Kotlin JSON-RPC Artifacts to Maven Local
        run: |
          mkdir -p ~/.m2/repository/xqt-kotlinx-lsp
          tar -xvf xqt-kotlinx-json-rpc-js-legacy.tar -C ~/.m2/repository/xqt-kotlinx-lsp

      - name: Setup Chrome Latest
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: 'latest'

      - name: Test for Kotlin/JS Legacy on Chrome
        run: gradle -D js.browser=Chrome jsLegacyBrowserTest
